complexdatacollective/Interviewer

src/components/ProtocolQuestion.js, src/containers/HomePage.js, src/index.js, src/styles/arbor/core/_reset.scss
Also catches a couple of style fixes and comments out conditional rendering.
=> Resolves #133. Adds a link to the sample protocol.

src/containers/Elements/PromptSwiper.js, src/containers/Elements/__tests__/PromptSwiper.test.js, src/containers/Elements/__tests__/__snapshots__/PromptSwiper.test.js.snap
=> Only show pips when prompts > 1

src/styles/components/_node-bucket.scss, src/styles/components/_node-layout.scss, src/styles/components/_panel.scss, src/styles/components/_sociogram-radar.scss, src/styles/containers/_name-generator-interface.scss
Goes along with https://github.com/codaco/Network-Canvas-UI/pull/32
Changes node size to be based on a CSS variable (node-base-size).
=> Use node base size variable

src/ducks/modules/network.js
This action is no longer used.
Resolves #301.
=> Remove addOrUpdateNode

src/utils/filesystem.js, src/utils/protocol/importProtocol.js
=> Load zip before prepping directories

config.xml, package-lock.json, package.json, public/package.json
=> Bumped to alpha 2

public/index.html
=> Add android poster security policy to img-src

config.xml, package.json, public/package.json, src/containers/SetupScreen.js
Just waiting on a name for this release.
=> update project versions

src/styles/components/_draggable-preview.scss, src/styles/components/_node-bucket.scss, src/styles/components/_node-layout.scss, src/styles/components/_panel.scss, src/styles/main.scss
Adds a small update to Network Canvas to override the new default font stack in the UI lib.
=> Override font stack 

public/protocols/development.netcanvas/protocol.json, public/protocols/education.netcanvas/protocol.json
Fixes #397. This just adds the missing uids as a temporary fix until #415 is ready.
=> add missing uids

src/behaviours/DragAndDrop/DragManager.js, src/behaviours/DragAndDrop/DragSource.js, src/containers/ConcentricCircles/LayoutNode.js, src/containers/ConcentricCircles/__tests__/__snapshots__/LayoutNode.test.js.snap, src/containers/NodeBucket.js, src/containers/__tests__/__snapshots__/NodeBucket.test.js.snap
Resolves #408.
This is obviously pretty subjective whether it improves the scroll/drag experience. It limits scroll movement to only consider initially vertical motion, or a ratio of velocity/angle for NodeLists, and leaves a horizontal scroll parameter for Ordinal Bin.
=> tweak scroll/drag

src/utils/protocol/protocolPath.js
This reverts the revert of window.require, matching state that's in master & fixing the failing test.
=> Revert additional winow.require

package-lock.json, package.json
Fixes #457. Depends on codaco/Network-Canvas-UI#50. Needs a package.lock update, probably.
=> get latest from ui

src/components/Setup/ProtocolCard.js, src/components/Setup/ProtocolCardList.js, src/components/Setup/__tests__/ProtocolCard.test.js, src/containers/ProtocolList.js, src/containers/Setup/SetupScreen.js, src/styles/components/_protocol-card.scss, src/styles/containers/_all.scss, src/styles/containers/_protocol-list.scss, src/styles/containers/_setupScreen.scss
This adds flex layout to the setup screen, and basic styling for protocols there.
=> Add basic styling to protocol list on Setup screen

.eslintrc.json
Resolves #396.
@jthrilly is this all you needed for #396? Or did you actually want to be able to write custom functions in the config file (in which case .js is the only option)?
=> Update .eslintrc to .json

src/containers/SettingsMenu.js, src/styles/components/_form-wizard.scss, src/styles/components/_modal.scss
Attempt to fix animation choppiness for #551 (using approach 2).
This will need testing on Pixel C hardware.
=> Fix animation choppiness on fullscreen modal form

src/containers/ConcentricCircles/__tests__/Background-test.js, src/containers/ConcentricCircles/__tests__/NodeLayout.test.js, src/containers/ConcentricCircles/__tests__/__snapshots__/Background-test.js.snap, src/containers/ConcentricCircles/__tests__/__snapshots__/NodeLayout.test.js.snap, src/containers/ConcentricCircles/propTypes.js, src/containers/__tests__/NodeBucket.test.js, src/containers/__tests__/__snapshots__/NodeBucket.test.js.snap, src/selectors/sociogram.js
- Rename `nodeBinSortOrder` -> `sortOrderBy`
- Update default for empty sort rule
=> Update references to nodeBinSortOrder to sortOrderBy.

src/containers/Setup/ProtocolUrlForm.js
This points the import URL at a working demo protocol.
=> Update import URL for working demo

public/protocols/development.netcanvas/protocol.json
=> Fix skipLogic syntax in development prototocol

src/components/Modal.js, src/styles/components/_modal.scss
This fixes the positioning and leverages portals, so Modal can effectively be higher in the dom and take z-index precedence over the timeline.
=> fix modal positioning

src/containers/OrdinalBins.js
=> Check node attributes for bin value

package-lock.json
From `npm install` on npm 6.4.1
=> Update resolved URLs in package lock

public/components/windowManager.js, public/electron-starter.js
Fixes a few things with the refactored Electron config:
- secure HTTPS communication to server
- links opening from app (Information screens)
- running in development mode
=> Fix electron setup

src/index.js
=> Prevent app from accepting dropped files/snippets

public/index.html, src/styles/components/_protocol.scss, src/styles/components/_timeline.scss, src/styles/components/main-menu/_main-menu.scss, src/styles/containers/_app.scss, src/styles/main.scss
=> remove viewport-fit:cover

src/styles/components/_server-card.scss, src/styles/components/_server-setup.scss, src/utils/serverAddressing.js
Also support leading zero-compressed addresses.
=> Allow users to enter IPv6 addresses

.travis.yml, public/protocols/development.netcanvas/protocol.json, schema/protocol.schema, scripts/schema/generate-schema.js
This should fix the CI errors on #781 and somewhat reduce conflicts with #774.
- Updates the schema to work with the new interface
- Remove generate-schema from the travis config
=> Fix schema for CategoricalBin Interface

package-lock.json, package.json, public/protocols/development.netcanvas/protocol.json, src/components/ListSelect.js, src/components/StageErrorBoundary.js, src/components/__tests__/__snapshots__/ListSelect-test.js.snap, src/containers/Interfaces/NameGenerator.js, src/containers/Interfaces/__tests__/NameGenerator.test.js, src/selectors/name-generator.js, src/styles/components/_list-select.scss, src/styles/containers/_name-generator-interface.scss, src/styles/containers/_name-generator-list-interface.scss
Fixes https://github.com/codaco/Architect/issues/317
Also fixes filtering on the name gen list interface.
=> update name generator to respect node type icon

src/components/Setup/ServerPairingForm.js, src/components/Setup/__tests__/ServerPairingForm.test.js
Similar to #784; the button on the pairing form needs type="submit".
=> Add submit type to pair button

public/components/appURL.js, public/components/mainMenu.js, public/components/windowManager.js
Fixes #742 by reverting to the previous reset data functionality.
=> fix data reset error on in progress interview session

src/containers/Interfaces/FinishSession.js
Fixes this export button (which is too small):
=> Fix export button size

public/protocols/development.netcanvas/protocol.json, src/components/Canvas/ConcentricCircles.js, src/containers/Canvas/Annotations.js, src/containers/Interfaces/Narrative.js, src/styles/components/_all.scss, src/styles/components/_annotations.scss, src/styles/containers/_all.scss, src/styles/containers/_narrative-interface.scss
Builds on #802, adding an annotation layer.
=> Narrative annotation layer

public/components/log.js
=> Re-enable electron logging in development

src/containers/Field.js
Fix props passed to placeholder hidden input component.
Resolves  #726
=> Fix hidden input placeholder.

src/components/CategoricalItem.js, src/components/__tests__/__snapshots__/CategoricalItem.test.js.snap, src/containers/CategoricalList.js, src/containers/__tests__/__snapshots__/CategoricalList.test.js.snap, src/styles/components/_categorical-item.scss, src/styles/components/_categorical-list.scss, src/styles/containers/_categorical-bin-interface.scss
=> Fix categorical bin rendering for window resize and unusual window sizes.

src/containers/withExternalData.js, src/utils/loadExternalData.js
=> Use source property to load external data

public/protocols/development.netcanvas/protocol.json, src/containers/Field.js, src/containers/__tests__/Field.test.js, src/containers/__tests__/Form.test.js, src/schemas/protocol.schema.v1.json
=> remove hidden input type

src/containers/MainMenu/TimelineStage.js
Fixes #864. Corrects the index for menu stage navigation, so filtering still navigates correctly.
=> fix index for menu stage filtering

src/containers/AlterForms/SlideFormEdge.js, src/containers/AlterForms/__tests__/SlideFormEdge.test.js, src/containers/AlterForms/__tests__/SlideFormNode.test.js, src/containers/AlterForms/__tests__/__snapshots__/SlideFormEdge.test.js.snap, src/containers/AlterForms/__tests__/__snapshots__/SlideFormNode.test.js.snap, src/containers/Form.js, src/containers/Interfaces/EgoForm.js, src/containers/Interfaces/__tests__/AlterEdgeForm.test.js, src/containers/Interfaces/__tests__/AlterForm.test.js, src/containers/Interfaces/__tests__/EgoForm.test.js, src/utils/__tests__/networkFormat.test.js
Adds tests for AlterForm, AlterEdgeForm, EgoForm, and related components.
=> add ego and alter tests

public/protocols/development.netcanvas/protocol.json, src/containers/Canvas/PresetSwitcher.js, src/containers/Canvas/__tests__/Annotations.test.js, src/containers/Canvas/__tests__/PresetSwitcher.test.js, src/containers/Interfaces/Narrative.js
Hides the "freeze" button when freeDraw is disabled for the protocol.
=> hide freeze button when free draw disabled

src/containers/Setup/ServerProtocols.js
Fixes #871. To verify, connect to Server and select a new Server protocol. It should prompt for a case ID, just as the existing protocols do.
=> add case id for server protocols

src/components/MainMenu/SettingsMenu.js, src/selectors/__tests__/interface.test.js, src/utils/protocol/accessors.js
Convert new protocol format into existing object format to minimise changes.
=> Update additional attributes format

.eslintignore, public/components/windowManager.js, src/components/MainMenu/MainMenu.js, src/components/MainMenu/MenuPanel.js, src/components/MainMenu/SettingsMenu.js, src/components/MainMenu/StagesMenu.js, src/containers/MainMenu/MainMenu.js, src/containers/MainMenu/__tests__/MainMenu.test.js, src/styles/components/main-menu/_main-menu.scss, src/styles/components/main-menu/_menu-panel.scss, src/styles/components/main-menu/_settings-menu.scss, src/styles/components/main-menu/_stages-menu.scss
Resolves #872. Adds an "Exit" button (if supported) and a toggle for full screen application (for electron).
=> add exit button and full screen app toggle

src/behaviours/AssetMetaProvider.js, src/behaviours/injectAssetUrl.js, src/containers/Interfaces/Information.js, src/protocol-consts.js, src/selectors/protocol.js
This updates the Information screen to use `assetManifest` for assets in `items[]`;
See also:
- Required protocol validation updates: https://github.com/codaco/protocol-validation/pull/5
- Update development protocol: https://github.com/codaco/development-protocol/pull/7
=> Use new content items format (assetManifest)

config.xml, src/components/MainMenu/SettingsMenu.js
Feedback request: increase max font size.
=> increase max font size

public/components/Updater.js, public/components/__tests__/Updater.test.js, public/components/__tests__/updater.test.js, public/components/mainMenu.js, public/components/updater.js, src/utils/__mocks__/dialog.js
- check for update on startup, but don't notify the user if none found
=> check for update on startup, but don't notify if none found

src/containers/Interfaces/FinishSession.js
This PR adds a prompt to the finish stage for when "delete after finish" is enabled, to ensure no accidental data loss.
=> prompt when finishing session and delete option is enabled

src/containers/App.js
Preview mode should bypass setting fullscreen state
=> fix fullscreen persistence for previewmode

src/containers/Interfaces/Narrative.js
=> Set allowPostioning to false if unset

src/containers/CategoricalList.js, src/containers/Interfaces/CategoricalBin.js, src/containers/__tests__/CategoricalList.test.js, src/containers/__tests__/__snapshots__/CategoricalList.test.js.snap, src/styles/components/_categorical-item.scss, src/styles/components/_categorical-list.scss, src/styles/containers/_categorical-bin-interface.scss
=> Make it easier to close categorical bins.

config.xml, package-lock.json, package.json, public/package.json
Contains:
- Fix for dialog cancel error
- URL decode protocol name
- Fix for consecutive alter form and alter edge form not submitting
=> bump version to 4.0.4

config.xml, package-lock.json, package.json, public/package.json
This release fixes a bug with protocol deletion: #961
=> bump version to 4.0.5

package-lock.json, src/selectors/__tests__/network.test.js, src/selectors/network.js, src/styles/components/_search.scss
This PR fixes an issue where the node label was not being correctly set when using external data.
=> Fix external data node labels

src/containers/Interfaces/FinishSession.js, src/utils/SaveFile.js
Add case ID for file export, to match Server's output. Resolves #1003.
=> customize graphml filename

src/ducks/modules/remote.js
Update Redux actions that are called during a remotely driven Network Canvas
=> Fix remote preview (for Architect)

src/ducks/modules/network.js
Squash rebase of the changes here because of merge conflicts: https://github.com/complexdatacollective/Interviewer/pull/1089
=> only allow boolean additional attributes

package-lock.json, package.json, src/components/Canvas/ConcentricCircles.js, src/components/Cards/ProtocolCard.js, src/components/Cards/SessionCard.js, src/components/SettingsMenu/Sections/ExportOptions.js, src/containers/Canvas/NodeBucket.js, src/containers/Interfaces/Sociogram.js, src/containers/LoadParamsRoute.js, src/containers/StartScreen/DataExportSection.js, src/containers/StartScreen/ManageProtocolsOverlay.js, src/containers/StartScreen/ResumeSessionPicker.js, src/utils/formatDatestamp.js
=> Fix console errors

package-lock.json, package.json
Tested the file access methods with Linux, but not other platforms.
Nothing in changelogs to suggest any other changes are needed.
=> Update electron to 9.4.4

package-lock.json, package.json, src/components/CategoricalItem.js, src/components/__tests__/__snapshots__/CategoricalItem.test.js.snap, src/containers/OrdinalBins.js
Updates to include the latest in UI, markdown for field labels/options. Also updates Categorical Bin and Ordinal Bin to allow for markdown in options.
=> allow markdown in field labels and options

src/containers/Canvas/PresetSwitcherKey.js, src/containers/Interfaces/Narrative.js
- Fixes some of the toggle options in the Narrative panels
- Adds markdown support to convex options.
=> Freeze narrative

src/ducks/modules/__tests__/installedProtocols.test.js, src/ducks/modules/installedProtocols.js, src/selectors/session.js, src/utils/protocol/checkExistingProtocol.js
Fixes #1134.
To test:
1. import a protocol to Interviewer
2. create a session
3. export to file or Server
4. attempt to re-import the protocol. This should give a warning, not an error.
=> update references to exportedAt

SECURITY.md, src/config.js, src/containers/Interfaces/DyadCensus/DyadCensus.js, src/containers/Interfaces/DyadCensus/Pair.js, src/containers/Interfaces/Narrative.js, src/containers/StartScreen/HeaderSection.js, src/ducks/modules/reset.js, src/selectors/canvas.js, src/styles/components/_information-interface.scss, src/styles/components/_node-form.scss, src/styles/components/_overlay.scss, src/styles/containers/StartScreen/_welcome-section.scss, src/styles/containers/_dyad-census.scss, src/styles/containers/_tie-strength-census.scss
- replace references to info@networkcanvas.com with references to https://community.networkcanvas.com/
=> update help references

README.md
Potential issues on running Interviewer on Apple M1 chip and ways to resolve them
=> Potential issues on running Interviewer on Apple M1 chip
