src/components/Menu.js, src/containers/SessionMenu.js, src/ducks/modules/menu.js
Adds a register and unregister session menu item. When you register an item, you pass in an object with an `id`, `title`, and `onClick` function. The `interfaceType` is optional, but currently defaults to `menu-custom-interface`. Session menu places it between `Reset` and `Quit` for now, in the order it is received.
=> adds register/unregister session menu item

src/containers/Elements/NodePanels.js, src/containers/Elements/__tests__/NodePanels.test.js, src/containers/Elements/__tests__/__snapshots__/NodePanels.test.js.snap
- Both panels can sometimes be valid, is that confusing?:
1. Node originally in 'previous' panel, dragged into main list
1. On a different prompt that node now shows in 'existing' panel, and again can be dragged to the main list
1. If that node is now picked up from the main list it can be a) dropped into existing to de-select prompt attributes b) be dropped into 'previous' to be deleted.
Fixes #275
=> Node panels only shows if panels accept the node type.

src/components/ListSelect.js, src/containers/Interfaces/NameGeneratorList.js, src/other/demo.canvas/protocol.json, src/selectors/name-generator.js
This updates the protocol api that the roster list uses. Cards and Sort buttons both use the provided labels instead of the variable names. Preparatory for #300.
=> update roster list protocol api

public/index.html, src/ducks/modules/errors.js, src/utils/protocol/assetUrl.js, src/utils/protocol/downloadProtocol.js
In Cordova attempt to load assets from factory location before the app data location.
This means that factory protocol assets should now load correctly
If a factory protocol name matched an imported protocol name, the factory protocol assets would be loaded (this is already the case for electron).
Resolves: #327 
Partial: #333
=> In Cordova attempt to load assets from factory location first

src/behaviours/withBounds.js
Cancellation was not working in conjunction with throttle.
Timer function should use either throttle or reqAniFrame (not both),
as throttle calls setTimeout internally.
Using throttle makes sense for 'infrequent' updates (where
`maxUpdatesPerSecond` much less than 60fps), and the API is clearer.
Fixes #328.
=> Fix withBounds() throttle cancellation

public/protocols/demo.canvas/custom.js, src/ducks/modules/mock.js
The network interface was simplified to reduce the number of actions.
This updates mocks (and the custom protocol JS) to use the new action.
Resolves #329.
=> Update mocks to use addNodes()

src/containers/StageMenu.js, src/styles/components/_menu.scss
This fixes the minor issue described in #352.
Before, user could see "previous" nav button in iOS, but would not lead to anywhere visible (it points to the Stage Menu filter).
With this change:
Resolves #352.
=> Hide Menu search when panel closes

src/containers/Interfaces/NameGenerator.js
Fixes #360.
Moving the Symbols for the forms to a class level variable keeps the name generators from clobbering each others' modals. Test by editing the protocol to have two NameGenerator interfaces one after another.
=> allow consecutive name generators to open node forms

src/containers/StageMenu.js
Fixes #362.
This allows the user to specify an `icon` in the stage's protocol to override the default icon for that interface in the menu. To test, edit the protocol to add an `icon` field set to one of the other available icons.
=> pass icon to menu item

src/containers/Interfaces/NameGenerator.js, src/selectors/forms.js
This updates the form lookup logic specified in #353. If a stage doesn't define a `form`, then the app attempts to use one whose name matches `subject.type`. If the chosen form key describes a non-existent form, then an error occurs.
Surfacing error to the user: #353 describes an optional error message to the user. I haven't included that yet, as I think we should discuss the best way to handle it. For now, I render the interface without any forms (or new form button), and a 'form' prop validation error displays in the client console. If we wanted to message the user about a missing form at render time, then this provides a logical point to add that.
=> Fix default form lookup

config/jest/automock.js, src/ducks/modules/__tests__/errors.test.js, src/ducks/modules/__tests__/protocol.test.js, src/ducks/modules/errors.js, src/ducks/modules/protocol.js, src/utils/protocol/__mocks__/index.js
This PR only has reducers tests for the protocol and error modules because I'm moving onto the Architect project.
Includes a working example for testing epics (rxjs/redux observables).
Partial: #386
=> Improved testing: Reducers

src/containers/Field.js
=> Removes isNumericOnly key from input props for non-text inputs.

package-lock.json, src/components/NodeList.js, src/containers/ConcentricCircles/EdgeLayout.js, src/containers/ConcentricCircles/Radar.js, src/containers/ConcentricCircles/__tests__/Radar.test.js, src/containers/ConcentricCircles/__tests__/__snapshots__/Radar.test.js.snap, src/containers/NodePanels.js, src/styles/components/_card.scss, src/styles/components/_dialog.scss, src/styles/components/_menu.scss, src/styles/components/_modal.scss, src/styles/components/_node-bin.scss, src/styles/components/_node-bucket.scss, src/styles/components/_node-list.scss, src/styles/components/_panel.scss, src/styles/components/_panels.scss, src/styles/components/_prompts.scss, src/styles/components/_search.scss, src/styles/components/_stage.scss, src/styles/containers/_app.scss, src/styles/containers/_name-generator-auto-complete-interface.scss, src/styles/helpers/_gpu.scss, src/styles/main.scss, src/styles/transitions/_transition--window.scss, src/styles/utils/_draggable.scss, src/utils/CSSVariables.js, src/utils/__mocks__/CSSVariables.js
Partially fixes #309 
While all the other instances of `palette` and `color` will compile to using `var`, we need to replace the values of colors that use SCSS functions like `transparentize` in order to use the css variables as expected.
https://github.com/codaco/Network-Canvas-UI/pull/37 should be merged in before merging this PR in.
=> Removing instances of transparentize to use css variables.

src/containers/Interfaces/Information.js, src/containers/Search/Search.js, src/selectors/name-generator.js
- Adds new selectors for sort orders for name generator
- Created a default property for `options` in Search interface
- checks for `items` before rendering them in Information interface
=> Fixes #364. Matches optional props checks with what wiki documents.

src/containers/NodeForm.js
Fixes #266. Triggers full screen modal (aka form wizard) when aspect ratio on device is below 1.6 *and* device height is below 1800px. The regular modal with the entire form should show if the aspect ratio is 1.6 or above, or the device height is 1800px or above.
This just tweaks the default until #390 can add a setting for user's preference.
=> tweak default for full screen modal

config/webpack.config.dev.js, config/webpack.config.prod.js, package-lock.json, public/components/log.js, src/utils/Updater.js, src/utils/filesystem.js, src/utils/getVersion.js, src/utils/protocol/downloadProtocol.js, src/utils/protocol/factoryProtocolPath.js, src/utils/protocol/importProtocol.js, src/utils/protocol/protocolPath.js
This is a PR onto the ui branch which targeted web and added `window.require`s for electron (needed to get things working with the new markdown dependency). 
Presumably we want to keep a single output target. `react-markdown` already includes a universal build, so this resolves the module to the UMD version via an alias.
- reverts 11a967d and 7af2bd3
- updates webpack config for dev & prod
If you want to rebase the other changes away in the ui branch & just cherry-pick the config change, 60190a2 is the commit you want.
Markdown rendering seems to work as I'd expect (testing Android and Electron).
=> Avoid having to `window.require`

package-lock.json, package.json
Network-Canvas-UI is good about adding tags to releases. This adds a version hash to the dependency, so that we can control when changes are introduced.
This will make it easier to work on outstanding fix & feature branches that require running `npm install` without introducing unrelated breaking changes. (Case in point: the open react-markdown branch.)
=> Pin UI dependency version

src/ducks/modules/__tests__/network.test.js, src/ducks/modules/network.js
This fixes #456, reverting TOGGLE_EDGE to add an edge if it doesn't exist already and remove it if it does exist. Also adds comments and updates the test.
=> fix can't delete edges

src/containers/NodeForm.js
Fixes #444. If you open the new node form in the education protocol, no warning about missing key for unique props should show now.
=> add key for items in list

public/protocols/education.netcanvas/protocol.json, src/containers/Interfaces/Information.js
Adds links and lists to markdown for Information Interfaces. Updates the education protocol to use markdown and not html. Resolves #453 since Josh updated the wiki.
=> update education protocol to use markdown

src/components/NodeList.js
Fixes #305. I think this does actually fix the issue with node lists displaying the previous prompt's nodes.
=> move cleartimeout to fix nodelist on quick prompt changes

src/components/ServerList.js, src/components/__tests__/ServerList.test.js
Names are still assumed unique. A subsequent advertisement for a name
replaces the earlier entry entirely. (For zeroconf-cordova, coalescing
happens at the library level; for electron, I haven't seen multiple
advertisements.)
Logs from a test run below. `fe80...` is a link-local address and so discarded; we don't get a usable IP address for the device API until `192.168.1.8`.
```
05-01 09:07:33.239  6512  6586 V ZeroConf: Initialized
05-01 09:07:33.239  6512  6586 D ZeroConf: Watch _network-canvas._tcp.local.
05-01 09:07:33.620  6512  6602 D ZeroConf: Added
05-01 09:07:33.621  6512  6602 D ZeroConf: Sending result: {"action":"added","service":{"domain":"local.","type":"_network-canvas._tcp.","name":"network-canvas","port":0,"hostname":"network-canvas._network-canvas._tcp.local.","ipv4Addre …
```
=> WIP: Reconcile multiple service advertisements

public/electron-starter.js, src/containers/SessionMenu.js, src/styles/main.scss
Mostly just pulling in the related change from Server here.
Including the built-in copy/paste menu items automatically adds keyboard shortcuts. This enables copy/paste across the entire app, which I assume is OK. The mac-specific handling is for the app menu item, as in [the electron docs](https://electronjs.org/docs/api/menu#main-process).
(Note that this also overrides Electron's default menu during development; if we were purposefully using different menus for dev/prod, then this may not be what we want.)
Fixes #489.
=> Support copy/paste in Electron

src/containers/LoadParamsRoute.js
This updates the LoadParamsRoute to render if `shouldResetState` is true.
I'm not sure this is the correct fix, but it seems to solve the following problem on `master`. If I'm viewing a session/protocol and then "Reset Session" (from side menu), the app renders a blank screen (and empty menus), and I'm forced to quit & restart the app.
=> Render from LoadParamsRoute if resetting state

src/ducks/modules/mock.js
Fixes "add mock nodes" from session menu. `networkActions` no longer contains `addNodes`.
=> Update mock node action to use sessions

public/electron-starter.js, src/containers/Interfaces/Information.js, src/utils/__tests__/markdownRenderers.test.js, src/utils/markdownRenderers.js
This adds:
1. a markdown link renderer to open anchor URLs in new windows. ReactMarkdown's link transformer already sanitizes things like `javascript:` URLs.
2. `new-window` handling so that URLs are opened in the user's default browser instead of a new electron window
Fixes #432.
=> Open content URLs in default browser

src/utils/markdownRenderers.js
Fixes a mistake I made in #504; `oneOfType` takes an array, not an arg list. I don't think this caused any issues at the user level, but was issuing console warnings/errors.
=> Fix PropType definition for markdown

src/containers/Interfaces/OrdinalBin.js, src/containers/OrdinalBins.js
Fixes ordinal interface rendering — the nodeAttributes action moved with the merge of latest master changes.
=> Import toggleNodeAttributes from sessions

src/selectors/skip-logic.js
This removes support for defining skip filters as function strings until we can implement safely and/or restrict the attack surface.
Based on discussion in #472, the need for custom functions in skip filters is 'less important'.  Until there's a safer implementation, users should use the object-based filter interface, as in the demo protocol example.
If approved, we should probably also update the wiki to remove mention of the 'functionized' string for now.
=> Ignore string-based skip filters

public/electron-starter.js, src/containers/SessionMenu.js, src/styles/components/_dialog.scss
- Renames reset menu item in web UI
- Adds native reset (redirects instead of reloading to clear path info)
- Uses "Develop" Menu to match Architect
Resolves #501.
=> Fix app reset

src/styles/components/_list-select.scss
Prompt text may overflow the top container; it should remain as
readable as possible but not capture click events from the main area.
Fixes #465
To test:
- optionally make a long prompt on the deom protocol's "NameGeneratorList"
- and/or view on a narrow screen
Tapping prompt text that overflows into filter controls on the list should no longer cause prompt to change.
=> Position list-select to capture interaction

src/styles/components/_panels.scss
Safari gives width to the flex child with display:flex, even when
there's no visible content inside.
Changing to block fixes the issue; flex isn't needed prior to
minimizing, since there's only a single panel containing the last
removable node.
Fixes #407.
Note: the issue does seem to be with nested flex layouts. In [another branch](https://github.com/codaco/Network-Canvas/tree/demo/safari-fix), I removed the nesting, which fixed the issue as well. Making that work with BEM would take more effort, but if the workaround in this PR is too hacky, there's at least that alternative.
=> Work around Safari width issue

src/components/Setup/ServerSetup.js, src/containers/Setup/ServerList.js, src/containers/Setup/__tests__/ServerList.test.js
If a hostname is unavailable from mDNS resolution, display an IP address of the server on the Server Card instead.
Partial fix for #510
=> Fall back to address for server label

src/behaviours/modal.js, src/containers/SessionMenu.js, src/ducks/modules/__tests__/sessions.test.js, src/ducks/modules/session.js, src/selectors/session.js
Fixes #512 and fixes #513.
- The "add mock nodes" button is hidden if there's no session/network to add them to
- Test coverage added for this case in the sessions reducer; failure state is still a throw
- A modal re-registers if (during component update) it detects it was unregistered while mounted. I think this is OK; the only case should be app data reset.
See issues for testing steps.
=> Fix session menu errors

public/electron-starter.js, src/index.js
- Disables pinch-to-zoom. Fixes #428.
- Adds standard menu items for zoom in/out/reset, which enables keyboard shortcuts requested in the above issue.
=> Fix zoom behavior

src/components/Card.js, src/components/CardList.js, src/components/__tests__/__snapshots__/Card-test.js.snap, src/components/__tests__/__snapshots__/CardList-test.js.snap, src/containers/SessionMenu.js, src/containers/Setup/SessionList.js, src/ducks/modules/__tests__/protocol.test.js, src/ducks/modules/__tests__/session.test.js, src/ducks/modules/__tests__/sessions.test.js, src/ducks/modules/protocol.js, src/ducks/modules/session.js, src/ducks/modules/sessions.js, src/styles/components/_card.scss, src/styles/containers/_setupScreen.scss
- Add "Return to start" item to sessions menu
- Add updatedAt timestamps to sessions; this seemed like a valuable data point to identify a session
- Other data matched from path
- Minor additions to CardList to accommodate display here (defaults are unchanged)
- Fix scrolling inside flex layout
- Card labels: I truncated the UUIDs for display; not sure if there's something better to display?
- Update UI submodule
=> Update sessions for new start screen

src/components/Card.js, src/components/__tests__/__snapshots__/Card-test.js.snap, src/containers/App.js, src/containers/SettingsMenu.js, src/containers/Setup/SessionList.js, src/containers/index.js, src/ducks/modules/__tests__/menu.test.js, src/ducks/modules/menu.js, src/selectors/__tests__/session.test.js, src/selectors/session.js, src/styles/components/_card.scss, src/styles/containers/_all.scss, src/styles/containers/_app.scss, src/styles/containers/_session-list.scss, src/styles/containers/_setupScreen.scss
- Rename session menu -> settings
- Add empty view for sessions (setup screen)
- Fix some small styling issues
=> Empty sessions view & setting menu

README.md, src/components/CardList.js, src/components/__tests__/__snapshots__/CardList-test.js.snap, src/containers/Setup/SessionList.js, src/styles/components/_card-list.scss
Provides a temporary interface ("x" button + confirm dialog) for removing interviews from the SessionList.
We expect to eventually re-work this interface to support dragging to a trash bin, so the "delete" functionality in Card doesn't need to stay, long-term.
=> Add delete button to session cards

src/components/NodeList.js
Fixes common case of #524.
If underlying sort isn't stable, and this isn't just a library issue, then this will need further refinement to prevent edge cases from cropping up.
=> Skip sort if no criteria given

src/components/NodeList.js, src/components/OrdinalBinBucket.js, src/containers/Interfaces/OrdinalBin.js
This change to NodeList sorts the nodes every time the props change, rather than on each render pass. I think this still covers the intended use case, and arguably sort no longer needs to be stable.
If this seems OK, we could do something similar with the ordinal bin (see #527).
Follow-up to #525. Fixes #524.
=> Sort nodes in list before render

src/utils/serverDiscoverer.js
Replaces zeroconf `unwatch` with `close`. This does additional teardown in JmDNS, and seems to fix service discovery after the component remounts. I did a little testing with reInit(), but I think this suffices, and is lighter touch.
I tested on a Nexus 5x phone; needs testing on at least a real tablet or two.
Edit: also tested iOS (iPad).
Assuming my original report (failed discovery on initial mount) is limited to emulators, this fixes #482.
=> Fix android MDNS discovery after remount

src/components/Setup/ServerCard.js, src/components/Setup/ServerSetup.js, src/components/Setup/__tests__/ServerCard.test.js, src/containers/Setup/ServerList.js
- Use instance from MDNS advert, as hostname isn't always available
- Refactor: ServerCard knows how to render the primary server label
- Use secondaryLabel (string) instead of children
To get the updated advertisement from Server, see the `fix/instance-name` branch there (https://github.com/codaco/Server/pull/103).
Fixes #510
=> Render server instance name, not hostname

src/__mocks__/request-promise-native.js, src/utils/__mocks__/filesystem.js, src/utils/protocol/__tests__/downloadProtocol.test.js, src/utils/protocol/__tests__/loadProtocol.test.js, src/utils/protocol/downloadProtocol.js
Tiny fix to ensure downloaded urls generate URI decoded paths.
Is marked as WIP because this needs to be tested on devices,
which is waiting on PR https://github.com/codaco/Network-Canvas/pull/533
=> Decode URI component for download urls for local paths

public/protocols/development.netcanvas/protocol.json, public/protocols/education.netcanvas/protocol.json, src/components/ListSelect.js, src/components/NodeList.js, src/components/OrdinalBinBucket.js, src/containers/ConcentricCircles/Background.js, src/containers/ConcentricCircles/NodeLayout.js, src/containers/ConcentricCircles/propTypes.js, src/containers/Interfaces/NameGeneratorList.js, src/selectors/__tests__/name-generator.test.js, src/selectors/name-generator.js, src/selectors/sociogram.js, src/utils/__tests__/sortOrder.test.js, src/utils/sortOrder.js
This adds a new sort generator in utils/sortBy, usage:
```
const sorter = sortBy([{property: 'name', direction: 'asc'}]);
const sortedItems = sorter(items);
```
The app has been updated to use this sort object everywhere orderBy-type
configuration is currently defined, with the exception of
NameGeneratorList which appears to sort by a single property and has
only been updated to accept the new object syntax: `{ property, direction }`.
Partially resolves: #108
=> Update Network Canvas to handle new orderBy syntax in protocols

src/components/Setup/ProtocolCard.js, src/components/Setup/ServerProtocolList.js, src/components/Setup/__tests__/ProtocolCard.test.js, src/components/Setup/__tests__/ServerProtocolList.test.js, src/containers/Setup/ProtocolList.js, src/containers/Setup/ServerList.js, src/containers/Setup/ServerProtocols.js, src/containers/Setup/SessionList.js, src/containers/Setup/__tests__/ProtocolList.test.js, src/containers/Setup/__tests__/__snapshots__/SessionList.test.js.snap, src/ducks/modules/__tests__/protocols.test.js, src/ducks/modules/errors.js, src/ducks/modules/protocol.js, src/ducks/modules/protocols.js, src/ducks/modules/rootEpic.js, src/ducks/modules/sessions.js, src/styles/components/_protocol-card.scss, src/utils/ApiClient.js
This implements the session export API call, part of #543.
We still need to design UI around export (which is #544, or possibly part of #543 if the 'resume' screen is migrating to a 'management' screen, and needs to coordinate with #529). For now, I've just added this to the existing 'remove' button as an example. If you've paired a server, and the protocol has a remote identifier, then the button will prompt you to export before removing.
To make this work for now, I've added a 'remoteId' to protocol actions, which gets picked up by the sessions reducer. As discussed in #545, sessions & protocols could be simplified where there are overlaps. We can tackle that here, but it may conflict with other related work.
To test this: use with the latest server branch `feature/protocol-versions`.
=> Initial data export

src/containers/Setup/ProtocolList.js, src/styles/containers/_protocol-list.scss
Looped nodes are cloned in DOM (outside of React). Fixes #557.
This removes looping from the protocol list. I experimented unsuccessfully with other settings in [swiper](http://idangero.us/swiper/api/). I'd like to avoid additional event handling outside of React, but if looping is required, then I can add that as described in the issue.
=> Remove looping on swiper

src/components/StageErrorBoundary.js, src/components/__tests__/StageErrorBoundary.test.js, src/containers/Stage.js, src/styles/components/_all.scss, src/styles/components/_error-boundary.scss
In the face of errors caused by stage loading or interaction (which is commonly happening as we update the protocol format), this allows user to continue or restart, rather than having to quit app or reset all data.
I think we've discussed using boundaries in places, but I don't see an issue filed. Apologies if this isn't what others had in mind — but it's making development with all of my [now outdated] protocol files easier.
=> Add basic error boundary for stages

src/components/Edge.js, src/containers/ConcentricCircles/EdgeLayout.js, src/containers/ConcentricCircles/__tests__/__snapshots__/EdgeLayout.test.js.snap
Fixes #398.
I'm not sure exactly what the issue was here — seems like a loss of precision until a full repaint is done — but using a larger viewBox seems to make iOS happy. I've tested iOS 11.4 sim [edit: and device (iPad Air)].
=> Use larger viewBox for Safari

config/jest/automock.js, public/protocols/education.netcanvas/protocol.json, src/containers/Interfaces/FinishSession.js, src/containers/Interfaces/__tests__/FinishSession.test.js, src/containers/Interfaces/index.js, src/containers/SettingsMenu.js, src/containers/Setup/SessionList.js, src/containers/Setup/__tests__/__snapshots__/SessionList.test.js.snap, src/ducks/modules/__tests__/protocol.test.js, src/ducks/modules/sessions.js, src/selectors/__tests__/skip-logic.test.js, src/selectors/interface.js, src/selectors/session.js, src/styles/containers/_all.scss, src/styles/containers/_finish-session-interface.scss, src/utils/ApiClient.js
Resolves #544.
- Adds a built-in 'Finish' interface to the end of all sessions
- Move 'export' functionality this interface
- Move 'download data' from menu to this interface
- Update session cards to display 'exported at' times
Notes:
- 'Download' always appears
- there are variants of Export display, but button only appears if a Server is paired & the session is exportable (has a remote protocol ID)
=> Add 'Finish' interface

README.md, public/electron-starter.js, src/containers/Interfaces/FinishSession.js, src/containers/Interfaces/__tests__/FinishSession.test.js, src/containers/LoadParamsRoute.js, src/containers/Setup/ProtocolList.js, src/containers/Setup/ProtocolUrlForm.js, src/containers/Setup/ServerProtocols.js, src/containers/Setup/SessionList.js, src/containers/Setup/__tests__/ProtocolList.test.js, src/containers/Setup/__tests__/SessionList.test.js, src/containers/Setup/__tests__/__snapshots__/ProtocolList.test.js.snap, src/containers/Setup/__tests__/__snapshots__/SessionList.test.js.snap, src/ducks/modules/__tests__/protocol.test.js, src/ducks/modules/__tests__/protocols.test.js, src/ducks/modules/protocol.js, src/ducks/modules/protocols.js, src/ducks/modules/session.js, src/ducks/modules/sessions.js, src/selectors/__tests__/protocols.test.js, src/selectors/__tests__/skip-logic.test.js, src/selectors/interface.js, src/selectors/protocol.js, src/selectors/protocols.js, src/selectors/session.js, src/utils/__tests__/matchSessionPath.test.js, src/utils/matchSessionPath.js
Resolves #545. Resolves #558.
This updates redux actions (with some minor changes to state shape) to better support protocol exporting and simplify some of the import/load/set flows with sessions. This builds on the FinishSession interface branch (a merge should wait on #559), but the two can be reviewed in parallel.
This also adds support for loading devtools extensions in electron (as redux-devtools was very useful for this effort), but installation left as a manual exercise (see Readme).
- Removes some of the differences between `loadFactoryProtocol` and `loadProtocol`
+ In particular, both now make use of `addSession()`
+ ...and session IDs are no longer generated by protocol actions
+ This reduces some of the coupling, but interfaces must call addSession in both cases now. (Unwanted …
=> Update redux for protocols & sessions

src/containers/Setup/ServerPairing.js, src/containers/Setup/ServerProtocols.js, src/ducks/modules/servers.js, src/ducks/modules/sessions.js, src/selectors/__tests__/servers.test.js, src/selectors/servers.js, src/utils/ApiClient.js, src/utils/__tests__/ApiClient.test.js
Resolves #541. This stores device credentials (ID & Secret, associated with a server) once pairing is complete.
For subsequent API requests, the client sends a token (ID). This uses the username part of HTTP Basic Auth (at least for now); this is only for identification. We'll eventually be using another mechanism to authenticate, but this lays some of the groundwork.
Because of CORS headers, this requires server-side changes (or API calls will fail); see [feature/device-tokens](https://github.com/codaco/Server/compare/feature/device-tokens).
=> Send token with API requests

src/containers/Interfaces/NameGenerator.js, src/containers/Interfaces/__tests__/NameGenerator.test.js
A prompt may define no form and have no default.
See #592.
=> Make node form optional

src/styles/components/_form-wizard.scss
Fixes #603.
I introduced this bug with #565; I hadn't tested a form that included "add another", which is part of the button container. This re-introduces flex layout to that container to prevent "Finish" from obscuring "Add Another".
The layout changes to the form itself remain, so I think the perceived animation jitter addressed by the earlier PR should remain OK.
=> Fix form wizard finish layout

src/styles/components/_card-list.scss, src/styles/components/_node-list.scss
When nodeList only contains one or two items, do not scroll them out of view.
Card list doesn't have the same issue since it doesn't have a min-height, but I changed both for consistency.
Issue:
=> Prevent unnecessary nodeList scrolling

src/components/Setup/ProtocolCard.js, src/styles/components/_protocol-card.scss
This fixes the positioning of the protocol card icon when used on the server protocol list.
before:
after:
Styling on the startup screen (the 'large' variant) should remain the same within a couple of pixels.
=> Fix standard protocol card styling

public/protocols/development.netcanvas/protocol.json, public/protocols/education.netcanvas/protocol.json
This is a small change to change "values" to "options" for the education protocol. Without "options", the Ordinal Bin for the education protocol was not loading. Development protocol was working, so I assumed "options" was the correct word here.
This also adds a missing variable type for "special_category" to the development protocol, so graphml will download correctly.
=> add missing values

public/protocols/development.netcanvas/protocol.json
Example: the form on the prompt titled "This is a prompt containing markdown".
=> Fix graphml download for data using special_category

src/containers/Field.js
Fixes #606.
To verify, look at the new node form in the development protocol, in both mobile and regular view. The hidden "timeCreated" field should not be visible, but present in the dom.
=> do not override type for hidden input

public/electron-starter.js
In development, if you've set a path to a load devtools extension that
includes a version number, and the extension is upgraded, the call to
addDevToolsExtension throws an error we should catch.
=> Allow electron to start even if dev extensions fail

src/components/Menu.js, src/containers/Interfaces/NameGeneratorAutoComplete.js
Resolves #466.
This removes the "esc" key listener from autocomplete and ensure that both session and stages menu respond to the "esc" key event.
=> escape only closes menu

public/protocols/development.netcanvas/protocol.json
This moves the initial static screens to the end of the interview. I spend a lot of time clicking past them or opening the stage menu to be able to work on other frequently-changing screens. (I've added "click the thing" to my music library in case I miss hearing it all the time.)
=> Re-order dev protocol

src/components/Pips.js, src/containers/FormWizard.js, src/containers/__tests__/__snapshots__/PromptSwiper.test.js.snap, src/styles/components/_pips.scss
Fixes #400.
Adds a "large" variant of the pips, used by the form wizard to distinguish from the prompt navigation.
=> Emphasize form wizard pips

src/ducks/modules/__tests__/network.test.js, src/ducks/modules/network.js
Fixes #437.
When a node is removed from the network, remove any edges that connected it.
=> When a node is removed, remove any connected edges

src/components/NodeList.js, src/components/OrdinalBinBucket.js, src/utils/__tests__/sortOrder.test.js, src/utils/sortOrder.js
This PR includes a few optimizations for node rendering:
- returning equivalent node objects from the sorter (removing the internal `createdIndex` prop)
- some minor adjustments to the sorter to avoid two extra mappings when they're not needed (I believe lodash already uses indexes to implement a stable sort internally). It's not a big deal, but could matter with external data sets.
- Update the comparison check in NodeList (https://github.com/codaco/Network-Canvas/commit/350dd01683faa41b02718c150caa570203ee7204). When nodes were sorted, this check always returned false.
+ with the above change to keeping node props unchanged, this isn't as big a deal, but it still seems cleaner
- I also updated tests to clarify existing LIFO/FIFO behavior
I think these changes are still equivalent to …
=> Reduce node re-rendering calls in sorted lists

public/index.html
This reverts an overly-aggressive CSP (connect-src) change I made in #613. The intent there was to prevent workers from making arbitrary network requests; worker scripts inherit the CSP of the app.
Of course, the app needs that flexibility in order to pair with arbitrary Servers, so I'm reverting for now. I'd like to investigate a way to keep that limitation on workers in the future; the CSP needs a review & update in general, so I'll open a separate issue for that.
=> Fix CSP for server pairing

src/behaviours/scrollable.js, src/components/Menu.js, src/components/NodeList.js, src/components/OrdinalBinBucket.js, src/components/__tests__/__snapshots__/CardList-test.js.snap, src/components/__tests__/__snapshots__/ListSelect-test.js.snap, src/components/__tests__/__snapshots__/Menu.test.js.snap, src/styles/components/_card-list.scss, src/styles/components/_menu.scss, src/styles/components/_node-list.scss, src/styles/components/_ordinal-bins.scss, src/styles/components/_panel.scss, src/styles/components/_protocol-card-list.scss, src/styles/components/_scrollable.scss, src/styles/containers/_interfaces.scss, src/styles/containers/_name-generator-auto-complete-interface.scss, src/styles/main.scss
This removes the dynamic visibility of the Scroller's top gradient mask. See discussion in #548.
In short, the scroller gradient mask is always visible, and scrollable clients ensure that they have enough top padding so that content isn't obscured when scrollTop is 0. This is managed through sass vars for now; if it seems burdensome, we can re-evaluate.
- fixed the scrolling behavior on NG Autocomplete
- reduced the bottom padding on `NodeList` so you can't scroll past all content in panels
I don't think `scrollTop` was needed. It was called by the NodeList, but I couldn't find a case where it would matter, since node props always appeared to change. If I'm wrong about this, please let me know; I have a local branch that had nearly restored support for it from the prototype.
There are two …
=> Remove dynamic state from scrollable

src/components/Transition/Search.js, src/styles/components/_search.scss, src/styles/containers/_name-generator-auto-complete-interface.scss
This updates Autocomplete styling to work with new menu. It adds a transition to the `right` property so that the search UI is centered within the interface.
=> Styling for the autocomplete list

public/electron-starter.js
Chalk is not included in production dependencies; require only in development.
=> Remove chalk dependency in production

public/protocols/development.netcanvas/protocol.json
Fixes #634. To verify, check and uncheck the checkbox on the development protocol's "NG Inputs" screen. It should be able to reopen the form and have the correct value for the checkbox.
=> initialize checkbox value

src/containers/ConcentricCircles/Radar.js, src/containers/ConcentricCircles/__tests__/Radar.test.js
This fixes rendering of the concentric circles when input type isn't a number.
Coerce strings to numbers when possible, but check for validity.
If NaN, the propTypes warning should still be logged to indicate why the circles are missing.
Fixes #632
=> Handle invalid input types to Radar

config/webpackDevServer.config.js, public/index.html, src/utils/WorkerAgent.js, src/utils/__tests__/WorkerAgent.test.js
Fixes #627.
The reported bug is with Chrome development, but this would be a problem with syntax errors in a user script as well.
If there's any syntax error in a worker script, then all clients making use of that worker will be notified of the failure, and the worker agent will reject any future requests. In the case of node labeling, this allows the Node container to fall back to the built-in label function.
Additionally, to make development mimic production a little better, I've disabled `historyApiFallback` in the dev server, which is what causes it to return index.html instead of 404s. This was the immediate source of the problem in #627. (This also uncovered a reference to a missing favicon, so I deleted that.)
1. Browser: `npm start` and view the education protocol in a browser. …
=> Better handling of syntax errors in user scripts

.travis.yml, config/webpack.config.dev.js, config/webpack.config.prod.js, package-lock.json, package.json
- Combines Travis jobs: We don't have the benefit of parallelism, and jobs are dominated by
boot & install overhead. (Contrast the `chore/travis-stages` run time [with others](https://travis-ci.org/codaco/Network-Canvas/builds).)
- Use [thread-loader](https://webpack.js.org/loaders/thread-loader/) for some loaders. This is used in more recent versions of create-react-app, and adopted in Server & Architect. On my machine, this speeds up dev & prod builds by 20-25%. I haven't seen any issues with it yet.
=> Make builds & CI faster

src/selectors/__tests__/forms.test.js, src/selectors/forms.js
Resolves #592.
This removes the feature that defaulted form to a form definition matching the node type. If the form prop is falsy, then no form should be displayed. (See https://github.com/codaco/Architect/issues/136). The Component prop is still optional, since `null` is treated as missing by PropTypes.
I've [updated the documentation](https://github.com/codaco/Network-Canvas/wiki/Name-Generator/_compare/6433ed7b9b012597e37a228f3a5ed1a9fc299ce8...a039a973b26847dd283b887ba2cd82ecb6320730) to match.
=> Remove fallback form behavior from protocol

src/components/CardList.js, src/components/ListSelect.js, src/components/__tests__/ListSelect-test.js, src/components/__tests__/__snapshots__/ListSelect-test.js.snap, src/containers/Interfaces/NameGenerator.js, src/containers/Interfaces/NameGeneratorAutoComplete.js, src/containers/Interfaces/NameGeneratorList.js, src/containers/Search/Search.js, src/ducks/modules/__tests__/network.test.js, src/ducks/modules/mock.js, src/ducks/modules/network.js, src/selectors/name-generator.js
This fixes remaining test failures, the CardList issue with Resume Interview, and some other issues with the secondary Name Generators (List & Autocomplete). I tried to stick to the new direction as best I could, but had to revert part of addNodes() to support those other name generators.
It's still not immediately obvious where the attributes sub-object needs to be dealt with in all cases, but I tried to add some test coverage for the problem spots I saw.
Summary by commit; they should be individually pickable:
- Fix session & node card lists
- CardList should provide an element of the supplied data collection for formatters.
- Fix Search (no results found)
- Search lib must be told where to find the nested attributes
- Fix node creation on NGList & NGAutocomplete
- Nodes already exist …
=> Fix model data issues

src/behaviours/__tests__/withPrompt.test.js, src/behaviours/withPrompt.js
Fixes #656.
One way to reproduce #656 (on master):
1. Start a session with the development protocol
2. Go to the third stage (ordinal bin with orange headers)
3. Double-click the 'next' timeline button (bottom left)
The promptIndex should be selected for the currentSession only when undefined (not 0). During the transition, the stage has already changed, and promptIndex may be out of range.
=> Fix prompt setting when index/ID is 0

src/containers/ConcentricCircles/NodeLayout.js
Fixes #657.
"meta" refers to node information; this checks the `.attributes` sub-object for layout info.
I don't see a straightforward way to add a regression test without a somewhat substantial refactor, so I've skipped that for now.
=> Fix node updating during drag

public/protocols/development.netcanvas/nodeLabelWorker.js, src/containers/Node.js, src/ducks/modules/__tests__/network.test.js, src/ducks/modules/network.js, src/selectors/interface.js
Fixes #668. Makes the sociogram cool again.
- the ID is added at the same level as user props
- to minimize conflicts and self-document, uses "networkCanvasId" as key
The node info provided to the worker will look something like:
```
{
"networkCanvasId":"2f92b04bbd7842d4ae90da7f2a1a178101f6ca51",
"support_friend":true,
"name":"Eustace",
"age":"24"
}
```
I've updated [the Node Labeling wiki](https://github.com/codaco/Network-Canvas/wiki/Node-Labeling).
=> Supply node UIDs to user workers

src/components/OrdinalBinBucket.js, src/components/__tests__/OrdinalBinBucket.test.js
This sets the `scrollDirection` prop on the wrapped nodes inside the Ordinal Bin Bucket to improve drag detection. The bucket is laid out horizontally but doesn't actually scroll, so `NO_SCROLL` is used.
I also removed the selectable/onSelect props since they're never used.
@rebeccamadsen thanks for the fix here.
=> Improve ordinal bucket item drag

src/containers/NodeBucket.js
Key is used to ensure that previous label is cleared when the next node
is ready to display. This is especially important for async node label
workers.
Fixes #667.
=> Fix key on bucket node

src/utils/__tests__/serverAddressing.test.js, src/utils/serverAddressing.js
MDNS may send back announcements containing only information that we consider to be invalid.
This doesn't mean discovery has failed; additional (or previous) announcements may contain the needed information. Returning null here allows discovery to proceed.
=> Add null check for apiInfo

config/webpack.config.dev.js
This changes eslint errors to warnings on the dev server, so that the webview logs style violations to the console instead of stopping the show with the error overlay. Errors are still treated as errors everywhere else (build log, CI, IDE & local linting).
@wwqrd added this to Architect & I copied it in Server. It makes development easier while keeping the strict lint settings.
=> Convert lint errors to warnings on dev server

src/utils/__tests__/filesystem.test.js, src/utils/filesystem.js, src/utils/protocol/importProtocol.js
Fixes #684. (Android & iOS.)
Test scenario:
1. Create a protocol package from the [development protocol source](https://github.com/codaco/Network-Canvas/tree/master/public/protocols/development.netcanvas)
- Rename the protocol by changing the "name" property in protocol.json
- Zip up contents & rename to *.netcanvas
2. Import this file to Server
3. Open NC in Android/iOS (actual device)
4. Pair with Server if needed
5. Import the created protocol
6. Wait
Expected: protocol is eventually imported successfully & displayed. Also note that (assuming you renamed the protocol in step 1) new sessions created from the imported protocol start quickly as expected.
Known issues:
- It's slow [on large assets]
- Could be worth experimenting with increasing the buffer size to reduce write calls, but …
=> Fix large asset import on Cordova

src/behaviours/DragAndDrop/DragPreview.js, src/behaviours/DragAndDrop/DragSource.js, src/behaviours/DragAndDrop/DropObstacle.js, src/behaviours/DragAndDrop/DropTarget.js, src/behaviours/DragAndDrop/__mocks__/reducer.js, src/behaviours/DragAndDrop/__mocks__/store.js, src/behaviours/DragAndDrop/__tests__/DropObstacle.test.js, src/behaviours/DragAndDrop/__tests__/reducer.test.js, src/behaviours/DragAndDrop/index.js, src/behaviours/DragAndDrop/reducer.js, src/components/Timeline.js, src/components/__tests__/Timeline.test.js, src/components/__tests__/__snapshots__/DropZone.test.js.snap, src/components/__tests__/__snapshots__/NodeList.test.js.snap, src/containers/ConcentricCircles/ButtonObstacle.js, src/containers/ConcentricCircles/ConcentricCircles.js, src/containers/ConcentricCircles/NodeLayout.js, src/containers/ConcentricCircles/PromptObstacle.js, src/containers/ConcentricCircles/__tests__/__snapshots__/ConcentricCircles.test.js.snap, src/containers/Interfaces/Sociogram.js, src/containers/NodeBucket.js, src/containers/ProtocolScreen.js, src/styles/containers/_sociogram-interface.scss
Resolves #371 and #469. This adds the notion of a `DropObstacle`. Currently, the "reset" button, prompt, timeline, and node bucket on Sociogram are obstacles, meaning nothing can be dropped on those components. This also makes Sociogram full screen again. The off-screen node drops in #469 were resolved by adding a render on dragEnd.
Feedback welcome as always.
=> Prevent node occlusion

src/containers/NodePanels.js, src/selectors/__tests__/sociogram.test.js, src/selectors/forms.js, src/selectors/interface.js, src/selectors/sociogram.js, src/selectors/utils.js, src/utils/protocol/__tests__/loadProtocol.test.js, src/utils/protocol/loadProtocol.js
Fixes #673. Fixes #674. Fixes #675.
This adds two points for validation to address the issues above.
- Adds a very basic validation step when loading a protocol. If no stages are defined, or the variableRegistry key is missing, loading will fail and the error dialog is displayed.
- This can be replaced by [schema validation](https://github.com/codaco/Network-Canvas/pull/644) in the future
- Adds `assert` to selectors. Failures here manifest as a message on the ErrorBoundary. This is currently applied in the following cases:
- If an interface requiring a node (subject) can't find the node definition in the registry
- If an interface [sociogram] requiring an edge can't find the edge definition in the registry
Two other null checks were added to match the 'lenient-input' approach elsewhere …
=> Fix error checking for certain protocol format issues

config/nc-dev-utils.js, src/behaviours/injectAssetUrl.js, src/utils/protocol/__tests__/assetUrl.test.js, src/utils/protocol/assetUrl.js
This is a short-term/partial fix for #681: the app will no longer crash or reload when dealing with assets from factory protocols. Specifically, the video in the development protocol should no longer cause issues; however, the change affects all assets including images & audio.
Downloaded (user-provided) protocols are still an issue; the difference is the relative location of the assets to the app source. Discussion in #681 will determine the best path forward.
I tested both production and dev builds on an iPad Air (12.0)& Nexus 5x (8.1).
=> Fix factory asset loading

public/components/log.js
Nothing is yet requiring this module, but if something does globally, we should not rely on the electron path existing. See https://github.com/codaco/Architect/pull/244.
=> Remove problematic logging config

src/components/Setup/ServerUnavailable.js, src/containers/Setup/ServerProtocols.js
This clarifies the "unavailable server" error messaging.
- Use "friendlyMessage" if defined
- Replace title text since error may be "permanent" (e.g., Unauthorized)
=> Improve server error message

src/components/Setup/ServerAddressForm.js, src/components/Setup/__tests__/ServerAddressForm.test.js, src/containers/Setup/ProtocolUrlForm.js, src/containers/Setup/__tests__/ProtocolUrlForm.test.js
Fixes #732, as well as the "manual entry" server form.
Cancel links were replaced by buttons; type needs to be specified since 'submit' is the default.
=> Fix form submit buttons

public/protocols/development.netcanvas/protocol.json, public/protocols/teaching-protocol.netcanvas/protocol.json, src/containers/ConcentricCircles/NodeLayout.js, src/selectors/sociogram.js
Fixes #731 
This was caused by sociogram incorrectly setting the value of toggled values, and using an incorrect protocol property not generated by architect.
=> remove highlight.value from factory protocols

public/components/windowManager.js
Same implementation as https://github.com/codaco/Server/pull/185:
While there is no intended mechanism to navigate away from the app URL within the app, this prevents any other (unexpected/untrusted) URLs from loading in the main window.
=> Prevent navigation away from app

src/containers/LoadScreen.js
Interim fix for #727.
`getDerivedStateFromProps` is called before every render (as of React 16.4), which means `setState()` triggers it, and if the protocol slowly enough then `minimumTimeMet` settles at `false`.
The change here boils down to removing the `prevProps.isWorking !== this.props.isWorking` check. This could be improved (as it may cause additional rendering), but should fix the immediate issue for now.
The easiest way to test is to download a protocol with assets on Android.
=> Fix load screen for slow protocol loading

src/utils/protocol/__tests__/importProtocol.test.js, src/utils/protocol/importProtocol.js, src/utils/protocol/protocolValidation.js
This checks the zipped file paths in a protocol before writing output to those paths.
To support [flexibility in the directory structure](https://github.com/codaco/Network-Canvas/wiki/Protocol-Overview), this detects problems. If we standardize on a top-level structure (perhaps moving worker scripts into `workers/`, then we could more easily check against a whitelist here, which is probably preferable.
=> Check protocol paths before unzipping

scripts/build.js
Build should not include test files
=> Skip tests when copying ./public during build

src/containers/Setup/ServerPairing.js, src/containers/Setup/__tests__/ServerPairing.test.js
This fixes pairing with Server; the prop name in redux changed.
To test: attempt to pair with a Server. (On master, will throw when the server icon is clicked.)
=> Fix device attribute from redux state

src/utils/filesystem.js, src/utils/protocol/assetUrl.js
Fixes #681 (large assets included in `download` protocols; the counterpart to #696).
This changes the asset URLs for all assets included in a downloaded protocol on Cordova:
- On Android, sets the asset URL directly from the saved protocol path
- On iOS, copies the asset to the device's tmp directory (for reasons discussed in #681)
To test: download (from Server or a URL) a protocol that contains large assets; for example, an external copy of the development protocol.
Limitations:
- As discussed in #681, this is intended as a temporary workaround until Cordova (or we) support `WKURLSchemeHandler` changes in the future
- Will not run in our [iOS & Android] development mode (i.e., the page must be loaded from `file://`)
To make protocols behave better in development, we could (for example) …
=> Fix downloaded asset URLs

src/components/Transition/Search.js, src/containers/Search/Search.js, src/styles/components/_add-count-button.scss, src/styles/components/_search.scss, src/styles/containers/_name-generator-auto-complete-interface.scss
This fixes the styling and animation problems described in #722, though I'll leave that open since discussion has started around a redesign there.
This also adjusts the width of the Search component to match the centering of other prompt content.
=> Fix autocomplete styling & animations

src/containers/Form.js, src/containers/NodeForm.js, src/containers/__tests__/Form.test.js
In NC-UI, a `Button`'s type now defaults to "button". This PR ensures the NodeForm will still be submittable once that UI change is included.
=> Specify "submit" on default form button

src/behaviours/__tests__/withPrompt.test.js, src/behaviours/withPrompt.js, src/components/MainMenu/SettingsMenu.js, src/containers/Interfaces/NameGeneratorAutoComplete.js, src/containers/MainMenu/SettingsMenu.js, src/containers/MainMenu/TimelineStage.js, src/containers/MainMenu/__tests__/MainMenu.test.js, src/containers/Node.js, src/containers/ProtocolScreen.js, src/ducks/modules/__tests__/network.test.js, src/ducks/modules/__tests__/sessions.test.js, src/ducks/modules/mock.js, src/ducks/modules/network.js, src/ducks/modules/sessions.js, src/selectors/__tests__/interface.test.js, src/selectors/interface.js, src/selectors/name-generator.js, src/selectors/protocol.js, src/selectors/session.js, src/utils/matchSessionPath.js, src/utils/protocol/accessors.js
This fixes the node information sent to worker label scripts; for example, from:
```json
{
"0e75ec18-2cb1-4606-9f18-034d28b07c19": "Dee",
"networkCanvasType": "4aebf73e-95e3-4fd1-95e7-237dcc4a4466"
}
```
to:
```json
{
"name": "Dee",
"networkCanvasType": "person",
}
```
Also fixes both node & edge information in the network passed to workers.
To test, you can replace the development protocol with [one that uses ID keys](https://raw.githubusercontent.com/codaco/Network-Canvas/chore/dynamic-validation/public/protocols/development.netcanvas/protocol.json).
Fixes #771. Fixes #719.
=> Fix worker node & edge props

src/ducks/modules/deviceSettings.js, src/utils/DeviceInfo.js
'device' may not be ready until after store is created. In this case, the device will now have an 'Undefined' name (and Android may use dynamic scaling by default).
This is an interim fix for #787 to prevent throwing. The actual desired behavior would be to ensure device settings is populated with correct values.
We could dispatch an 'initialized' event from `startApp`, but it's possible that would fire after rehydration, in which case we might overwrite user preferences. So we'll either need to change when the store is initialized, or treat anything matching a static initialState as not user-set.
=> Ensure device is defined before reading

src/containers/LoadParamsRoute.js, src/ducks/modules/__tests__/deviceSettings.test.js, src/ducks/modules/deviceSettings.js, src/ducks/modules/reset.js, src/ducks/modules/rootReducer.js, src/index.js, src/utils/DeviceInfo.js
Fixes #787. This is a follow-up to #788. Rather than creating the store & reducers lazily, I've taken the second approach described in 788.
- initialState is statically determined
- a `deviceReady` action is dispatched prior to `ReactDOM.render` to set better defaults based on runtime info
- Does not interfere with rehydration or user settings
The lazy creation approach should work fine, but this seemed slightly preferable to me.
=> Fix device settings on startup

scripts/schema/generate-schema.js, src/schemas/protocol.schema.v1.json
Subtask from #785. CardOptions [should not require additionalProperties](https://github.com/codaco/Network-Canvas/wiki/Name-Generator:-Roster-List#interface-specific-api). Architect behaves correctly in https://github.com/codaco/Architect/pull/338.
=> Do not require additionalProperties for cards

src/ducks/modules/sessions.js
If a user attempts to export a session without having made other calls to
the API first, we need to ensure the main process is aware of the
pre-trusted certificate.
=> Fix cert errors with session export

src/containers/Field.js, src/containers/__tests__/Field.test.js, src/selectors/__tests__/forms.test.js, src/selectors/forms.js
Fixes #819.
This restores values to hidden inputs defined by a protocol. There are two parts to this:
- Change the return type of `getDefaultFormValues`. Based on the [`NodeForm` usage](https://github.com/codaco/Network-Canvas/blob/1aee497e17883e080fad714d9cf01ae9cb309ba4/src/containers/NodeForm.js#L89), I'm pretty sure this was the intent.
- Populate the value from the `input` prop. Based on [Redux Field docs](https://redux-form.com/6.0.0-alpha.4/docs/api/field.md/), I think this is what we'd expect, but I'm not very familiar with redux form, so I could be off here...
When using the app, I'm expecting that the form input contains the value, and that the generated node contains the corresponding attribute.
=> Fix hidden input values

src/containers/Canvas/NodeLayout.js
With the update to allow multiple highlight attributes to support Narrative interface, toggle highlight was not updated. This updates the toggle for highlighting attributes.
To test, in master you cannot toggle attributes on Sociogram prompts; it toggles "undefined" instead of a valid attribute. Here, you can toggle the correct attribute as expected.
=> make sure highlight attribute updates the right attribute

config.xml, package-lock.json, package.json
The `maxSdkVersion` property is causing the app to not be installable on API level 28 devices. As per [the documentation](https://developer.android.com/guide/topics/manifest/uses-sdk-element), there is no need to set this property (and in fact it is a bad idea).
In classic Cordova fashion, there was a bug in both our previous and the current version of the android platform, which has required updating to a specific version in order to make this property be correctly built into our compiled APK.
=> remove android-maxSdkVersion from config.xml

src/containers/Interfaces/AlterEdgeForm.js, src/containers/Interfaces/AlterForm.js
Removes `allowTouchMove` option from swiper, and instead uses the `swiper-no-swiping` class so our mouse/touch events still register as expected for forms.
=> fix touch/mouse issue

src/schemas/protocol.schema.v1.json, src/selectors/__tests__/interface.test.js, src/selectors/interface.js
Fixes #870. This ensures that `null` categorical and ordinal `options` are handled gracefully, and adds a test for that. 
To check, remove options from the variable registry for a categorical or ordinal variable used in an interface, and see that the interface still loads.
=> default for options

src/selectors/network.js
Very small change for narrative preset key, which was expecting a `label` for variable attributes. It should look for a `name` now.
=> fix blank narrative attribute label

src/selectors/__tests__/skip-logic.test.js, src/selectors/skip-logic.js
Fixes skip logic to work without a top level operator expectation.
=> remove top operator from skip logic

src/containers/Canvas/PresetSwitcher.js, src/containers/Interfaces/Narrative.js, src/containers/Interfaces/OrdinalBin.js, src/containers/OrdinalBins.js
This fixes the narrative error when highlight variable is not provided, defaulting to an empty array.
Also fixes ordinal bin issue when a value is set to `0`. The value was being set correctly, but the bins were just not displaying it because `0` is `false`. Checks for null or undefined to test whether a value is filled in or not when filtering nodes for ordinal bins.
=> missing highlight and zero value ordinal

src/containers/Setup/SetupScreen.js, src/styles/components/_session-list.scss
Feedback response: rename the start screen labels to "Manage Interview Sessions", and "Start New Session".
Also creates transparent background color for manage sessions screen in UI.
Also updates UI ref.
=> rename start screen screen labels

config.xml, package-lock.json, package.json, public/index.html, src/components/MainMenu/SettingsMenu.js, src/containers/App.js, src/ducks/modules/__tests__/deviceSettings.test.js, src/utils/DeviceInfo.js
Fixes #900.
The behavior with iOS viewports is complicated, and we have changed it several times to address different issues. In #334 we removed a meta viewport property that makes iOS scroll to a focused input because it was causing content to be pushed off of the screen.
In this PR I add a Cordova plugin that makes iOS behave the same way as Android, which is to shrink the viewport when an input is focused. This means the above issue no longer occurs, and the property can be reinstated.
As a consequence, iOS can no longer use viewport units for font sizing. I updated the default device setting to reflect this. I also removed the ability to set dynamic font sizing on Cordova entirely, since it will break the app. I actually think having all mobile on PX sizing, and all electron on …
=> add cordova keyboard plugin, switch iOS to px font sizing

src/containers/ProtocolScreen.js
Feedback response: this removes the rotateIndex that caused the interview to return to the start when clicking next at the end, and to the end when clicking back from the start.
=> stop the interview navigation from looping round

src/components/MainMenu/SettingsMenu.js, src/ducks/modules/importProtocol.js, src/utils/protocol/checkExistingProtocol.js, src/utils/protocol/parseProtocol.js
This is a super low involvement implementation of this. Instead of refactoring and removing the UUID generation that is littered throughout the importProtocol thunks, I added two functions to identify the filename, and injected it into the protocol payload after it is parsed. 
Todo:
=> Remove protocol.name from Network Canvas

src/containers/ProtocolScreen.js, src/selectors/skip-logic.js
This ensures we don't skip past the beginning or end of a protocol, stopping at the current index if there are no more unskipped stages remaining.
=> Skip logic not to skip past the first or last stage

src/containers/Interfaces/Narrative.js
Fixes #879. To check, create a protocol with no behaviors toggled (so freeDraw is undefined, not false). The "freeze" button (snowflake) should not display. With a protocol like development protocol that has freeDraw toggled true, the snowflake should display still.
=> freeze button should not show when no freeDraw

src/ducks/modules/__tests__/dialogs.test.js, src/ducks/modules/dialogs.js
This PR fixes an issue that causes the app to crash when clicking the cancel button if an `onCancel` event handler is not present in a Dialog.
=> correct typo in onCancel handler

src/ducks/modules/__tests__/sessions.test.js, src/ducks/modules/sessions.js
Fixes #960. Makes sure we keep `sessions` as an object in redux, not converting it to an array. To test, add two protocols with sessions for each. Delete one of the protocols, and make sure `sessions` still is an object with the uuids as keys. You could also verify by exporting a remaining session and ensuring the overview for sessions lists the expected uuids.
=> keep sessions as an object

src/selectors/network.js
This PR sorts fallback variables used for node labelling, to ensure the one that is picked is consistent.
Fixes a bug a user reported where, when previewing a protocol in Architect, a gender variable was being used as a label. However, when the same protocol was viewed in NC the variable they had intended was being used for labels instead.
It turned out that the root cause of this was that the user had no variable called `name` in the codebook, and the sequence of the fallback variables was different between NC and Architect. Thus, NC in preview mode was selecting a different fallback variable than NC standalone. We believe this to be due to non-deterministic ordering of object properties in JS.
Initially we used `sort()` on the filtered fallback variables list, ensuring consistency. …
=> Remove fallback node label handling, and display instructive label to users

src/styles/containers/_app.scss
User reported an error when opening the app on an older iPad running iOS 10.3.3. Was able to repro:
After fix:
Fix was to remove display:flex from `app__content`. Unclear on why this is the cause of the issue, and the property should be required. This will need testing cross platform to ensure it doesn't break things for other users.
=> Fix startscreen bug in iOS 10

src/components/Setup/ProtocolCard.js, src/styles/components/_protocol-card.scss
- Uses info/notice colouring/icon on the outdated protocol card.
- Downgrades dialog to a notice, reframes the title, and rewording of the text.
Resolves https://github.com/codaco/Network-Canvas/issues/981
=> Deemphasise outdated protocol notice

src/ducks/modules/navigate.js, src/selectors/session.js
New navigation changes didn't take into a potential account lack of finish screen (which is omited in preview mode).
This change adds a `screenCount` which is separate from `stageCount` to take into account the additional screen.
=> Fix navigation to take into account lack of finish screen

src/components/Canvas/ConvexHulls.js, src/selectors/__tests__/canvas.test.js, src/selectors/canvas.js
Nodes are grouped by categorical variables in the `makeGetNodesByCategorical()` selector, meaning that numerical values are considered as strings. When the group value was searched for in the schema options they didn't match.
Have updated the selector to return in the format:
```js
const nodesByGroup = {
[groupName]: {
group: groupName,
nodes: [ ... ],
},
...
}
```
**Please note**
This PR fixes tests relevant to the changes, but there are pre-existing failing tests on master.
Resolves #1020
=> Fix convex hull color sequencing

src/containers/ProtocolScreen.js, src/containers/SlidesForm/SlidesForm.js, src/hooks/__test__/useGetFormName.test.js, src/hooks/useGetFormName.js
Generates new form name based on changing `stage.id`
When navigating between AlterForms (and AlterEdgeForms), form names clashed.
When the interface changed, the new forms were initialized properly (with initialValues), but were subsequently being destroyed as the forms from the previous stage were deinitialised.
=> fix form empty initialValues

src/components/FilterableListWrapper.js
Fixes #1034. The error when trying to filter sessions is just from items in the session parameters being null or undefined, so this just makes sure we don't choke on those comparisons.
=> handle null list items

src/containers/Interfaces/DyadCensus/DyadCensus.js, src/containers/Interfaces/DyadCensus/useSteps.js, src/styles/containers/_dyad-interface.scss
This is a fix for an error on the DyadCensus stage. After resetting App Data, I saw this error on the DyadCensus stage of the development protocol: `TypeError: Cannot destructure property 'step' of 'undefined' as it is undefined`. This seems to fix it for me, unless someone has a better solution.
=> fix useSteps for dyadCensus

config/jest/automock.js, package-lock.json, package.json, src/__mocks__/electron-log.js
Version 9.0.0 of electron changes IPC behaviour which requires an electron-log update.
=> Update electron-log to fix ipc warnings

src/containers/ProtocolScreen.js, src/containers/SlidesForm/SlideFormEdge.js, src/containers/SlidesForm/SlideFormNode.js, src/containers/SlidesForm/SlidesForm.js, src/containers/SlidesForm/__tests__/__snapshots__/SlideFormEdge.test.js.snap, src/containers/SlidesForm/__tests__/__snapshots__/SlideFormNode.test.js.snap
Resolves #1025.
Steps to reproduce the issue:
0. create a protocol with a name generator and an alter form that has a text field.
1. add protocol and start a new interview in NC.
2. add a node.
3. navigate to the alter form.
4. Click next arrow to get past the intro to first node on the alter form.
5. Mouse in to the text box and hit enter on the keyboard. Will not move to the next stage and says "2 of 1" at the bottom progress bar.
Basically, pressing the enter key in a form uses the redux hidden submit button to submit the form, bypassing all of our `beforeNext()` logic. The `beforeNext()` logic checks to make sure it's okay to submit a form, and whether we move to the next stage or simply the next node in the current stage. So this makes sure that logic actually still happens before …
=> make sure beforeNext runs on enter pressed

src/ducks/modules/mock.js, src/ducks/modules/sessions.js
A protocol without an ego entry would load in NC, but not allow a new session to be started. This fixes that, and also makes sure protocols missing ego/nodes/edges in their codebooks can still create mock sessions.
To test, create a protocol without any ego stages, add to NC as a protocol, and click "start new interview".
=> allow missing ego from codebook

package-lock.json, src/styles/containers/StartScreen/_export-error-list.scss, src/utils/ApiClient.js, src/utils/exportProcess.js, src/utils/networkFormat.js
Updates Interviewer to send include `codebookHash` in the session variable properties sent to `network-exporters` and to Server via the API.
Updates the network exporters submodule to encode this data correctly in graphml files.
=> implement codebook hash in sessionVariables

package.json
- Updates network-exporter to use copy rather than rename
- Update package.json to include snap build
Requires: https://github.com/complexdatacollective/network-exporters/pull/26
=> Fix snap package

build-resources/scripts/bonjour.nsh
Makes sure to skip the bonjour installer if the user answers no to "Do you want bonjour", so they aren't asked twice.
=> skip bonjour if answer is no

src/components/NewFilterableListWrapper.js, src/containers/StartScreen/DataExportSection.js
This change allows filter to operate around export and select all options.
This works by updating `<NewFilterableListWrapper />` to expect list filtering to be managed externally if the `onFilterChange` prop is provided.
- The "original" selection is remembered until you make a change:
- If you select a toggle, it will only apply that feature to the visible range
- If you select an individual session it will only change the selection of that individual session, filtered but hidden sessions will remain selected.
- Toggle state is dependent on visible range, if select all or unexported sessions do not match those in the visible range they will be toggled as "off" until that changes.
Resolves https://github.com/complexdatacollective/Interviewer/issues/1117
=> Update NewFilterableListWrapper to support external filter and change behaviour

src/containers/Canvas/PresetSwitcherKey.js, src/containers/Canvas/__tests__/PresetSwitcherKey.test.js
Fixes case where `preset.highlight` is empty, and anticipates `preset.edges.display` also potentially being empty.
=> Assume preset.highlight and preset.edges.display can be empty (master)

config.xml, package-lock.json, package.json, public/package.json
This release contains a fix for a small bug that impacts updating an already installed protocol. It should be installed by all users currently running version 6.1.0. 
If you are running a version prior to 6.1.0, please consult the release notes for that release before updating: https://github.com/complexdatacollective/Interviewer/releases/tag/v6.1.0
- Fixed an issue where the app would incorrectly inform a user that there were in-progress sessions when attempting to import a protocol.
=> Release branch for 6.1.1

src/containers/CategoricalList/CategoricalList.js
Will desaturate a category if the value is less than zero or the string 'other'.
There are two different styles, the latest version closely resembles ordinal bins, but I think the initial style from 5ca73e1 was better (see individual commits).
Resolves #1115
=> Desaturate categorical

src/hooks/__test__/useSort.test.js, src/hooks/useSort.js
Very small fix which should resolve sort controls not working in SearchableList.
Also added a test to back it up.
Resolves #1148
=> Fix Searchable List sort controls

src/containers/StartScreen/ServerAddressForm.js, src/containers/StartScreen/ServerSection.js
This updates a couple of broken documentation links.
I do still have an error when attempting to install the Sample Protocol, so still looking at that if anyone has thoughts.
`RequestError: Error: certificate has expired`
=> correct stale documentation links

src/containers/withExternalData.js, src/hooks/useExternalData.js
Somehow we applied the type correction for cvs data to name generators, and not large and small rosters. This adds it in for rosters as well.
=> type correction for rosters too

config.xml, package-lock.json, package.json, src/utils/storageAdapters.js
The steps that seem to resolve this have no relationship to the initial error message I found, but here is what I did:
- Upgraded cordova-sqlite-plugin to 6.0.0 which fixes some issues with
Android SDK 30 (which the broken devices are running).
- Updated the implementation of the above plugin to use the android
system database provider
Needs testing to verify the fix, as well as to ensure no other issues have been introduced here.
As part of fixing this I had to remove and add cordova stuff loads of times, so this PR lacks cordova-ios. We need to add that back in.
We also need to test that this doesn't break things on iOS, although since this won't be a release for any other platforms it isn't crucial that we address any issues related to this now.
=> Fix crash on startup on android devices

.github/workflows/dist.yml, .github/workflows/main.yml, package-lock.json, package.json
This PR updates the github actions to support python 3, since 2.7 was removed. Required updating `node-sass`, and `sass-loader` to extremely specific versions.
Python 3.11 is NOT supported, due to a bug with node-sass, which cannot be updated further.
=> upgrade to support python 3

package-lock.json, package.json, src/containers/NodeForm.js, src/containers/QuickNodeForm.js
Fixes a bug where additional nodes could be added on name generators with forms after the max nodes had been added.
- This was due to the button still being clickable even if it appeared disabled.
- Decided to fix in codaco/ui instead of handling this here. Implemented in https://github.com/complexdatacollective/Network-Canvas-UI/pull/208 .
- This PR updates the ui package to 5.8.5 which fixes this issue, and removes the checks within the onclick function for disabled as they are no longer needed.
=> fix/ action button still clickable after max reached

config.xml, package-lock.json, package.json, public/package.json, src/utils/__tests__/createSorter.test.js, src/utils/createSorter.js
Users have been able to configure rules for sorting by categorical variables in Architect, but they were being sorted as strings. **This PR fixes sorting functionality for categorical variables to actually sort by the values provided.**
The hierarchy for sorting is _determined by the order that the values are defined_ in the variable definition. This user-supplied hierarchy is assumed to be _high to low_, to maintain consistency with the hierarchy sort used currently for sorting by ordinal variables. 
In cases of items having multiple values in a category array, _presence of a category is ranked higher than absence of_. For instance [“A”, “B”] is considered higher in the hierarchy than [“A”].
=> Fix/ sort by categorical variables
